### PR TITLE
Reduce boxing for primitives and value classes

### LINKED ISSUE #57: [Bug]: AnimatedNumber and AnimatedVector2 creating huge amount of Float and Offset objects
### What happened?

...which results in large memory footprints when playing animation, and frequently triggers garbage collect with a fairly simple Lottie animation. In my case it's collecting 24MB every ~1s, and the allocations profiler shows thousands of Floats and Offsets are created every time it refreshes. Inspecting the stack trace reveals that, in [AnimatedTransform.matrix()](https://github.com/alexzhirkevich/compottie/blob/standalone-main/compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedTransform.kt#L89) which is called very frequently by [draw() calls of BaseLayer](https://github.com/alexzhirkevich/compottie/blob/standalone-main/compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/BaseLayer.kt#L163) there are a lot of Float/Offset boxing and unboxing going on.

### What Compottie version do you experience the bug on?

2.0.0

### What platforms are you seeing the problem on?

Android

### Does Compottie log anythyng to the stdout / your logger set with `Compottie.logger`?

```shell

```

### PR DESCRIPTION
**Pull request by alexzhirkevich**
Fixes: #57

### CODE REVIEW

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt [hunk 1]
```diff
@@ -25,18 +25,21 @@ internal sealed class AnimatedColor : ExpressionProperty<Color>() {
 
     abstract fun copy(): AnimatedColor
 
-    override fun mapEvaluated(e: Any): Color {
+    override fun mapEvaluated(e: Any): Color = Color(mapColor(e))
+
+    override fun mapColor(e: Any): ULong {
```
Comment (tindy2013) [inline compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt]: ULong is not a primitive type, it is a value class with Long as underlying data. Using it like this still causes excessive boxing

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt [hunk 2]
```diff
@@ -15,100 +15,123 @@ internal class BaseKeyframeAnimation<T : Any, K, KF : Keyframe<K>>(
...
-                ),
-                requireNotNull(
-                    endHold ?: sortedKeyframes.getOrNull(1)?.start,
-                    InvalidKeyframeError
-                ),
-                0f,
+    private val firstFrame: Float = if (keyframes.isEmpty()) 0f else keyframes.first().time
+    private val lastFrame: Float = if (keyframes.isEmpty()) 0f else  keyframes.last().time
+
+    protected val keyframesMappingRanges : Map<Int, Pair<K?,K?>> = if (keyframes.isNotEmpty()) {
```
Comment (tindy2013) [inline compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt]: Using nullable primitive/value class and generic type container will cause boxing, this should be a custom container type with key specified as Int type, and use a special value to represent non-existent instead of null

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt [hunk 3]
```diff
@@ -305,24 +306,27 @@ internal class TextLayer(
...
         fillPaint.alpha = fillProperties.alpha
 
-        val strokeH = textAnimation?.style?.strokeHue?.interpolated(state)?.coerceIn(0f, 360f)
-        val strokeS = textAnimation?.style?.strokeSaturation?.interpolated(state)?.coerceIn(0f, 1f)
-        val strokeB = textAnimation?.style?.strokeBrightness?.interpolated(state)?.coerceIn(0f, 1f)
+        val strokeH = textAnimation?.style?.strokeHue?.interpolatedFloat(state)?.coerceIn(0f, 360f)
+        val strokeS = textAnimation?.style?.strokeSaturation?.interpolatedFloat(state)?.coerceIn(0f, 1f)
+        val strokeB = textAnimation?.style?.strokeBrightness?.interpolatedFloat(state)?.coerceIn(0f, 1f)
 
         strokeProperties.color = if (strokeH != null && strokeS != null && strokeB != null) {
```
Comment (tindy2013) [inline compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt]: Checking nullability on primitive type will cause boxing

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt [hunk 4]
```diff
@@ -305,24 +306,27 @@ internal class TextLayer(
...
-            textAnimation?.style?.strokeColor?.interpolated(state)
+            textAnimation?.style?.strokeColor?.interpolatedColor(state)
+                ?.let(::Color)
                 ?: document.strokeColor?.toColor() ?: Color.Transparent
         }
 
-        strokeProperties.color = textAnimation?.style?.strokeColor?.interpolated(state)
+        strokeProperties.color = textAnimation?.style?.strokeColor
+            ?.interpolatedColor(state)
+            ?.let(::Color)
```
Comment (tindy2013) [inline compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt]: Why `strokeProperties.color` is set the second time here?

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt (hunk 2 above)
Comment (alexzhirkevich) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt]: This should be boxed one time during init and unboxed on every frame which is fine, isnt it?

Comment (tindy2013) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt]: but looking up frame id in map may cause id to be boxed in Integer and call Map.get(Object)

Comment (alexzhirkevich) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/BaseKeyframeAnimation.kt]: Replaced with `androidx.collection.IntObjectMap`

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt (hunk 1 above)
Comment (alexzhirkevich) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt]: replaced with long

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt (hunk 3 above)
Comment (alexzhirkevich) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt]: Replaced with elvis

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt (hunk 4 above)
Comment (alexzhirkevich) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/layers/TextLayer.kt]: removed

File: compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt [hunk 5]
```diff
@@ -114,13 +139,22 @@ internal sealed class AnimatedColor : ExpressionProperty<Color>() {
...
+                ?.interpolatedColor(state)
+                ?: 0L
         }
     }
 }
 
-internal fun List<Float>.toColor() = Color(
+internal fun Color.toColorLong() : Long {
+    return (value shr 32).toLong()
+}
```
Comment (tindy2013) [inline compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt:155]: It looks kind of weird, although that's what the helper fun in compose do for long color. I would recommend directly convert to and from ULong, and create another helper fun Long.toColor()

Comment (tindy2013) [reply compottie-core/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedColor.kt:155]: using `value.toLong()` directly also get rid of a call to `ULong.constructor-impl()`
