### PR TITLE
Don't crash in MutableList<Float>.fill(color : Color) in AnimatedText…

### LINKED ISSUE #17: [Bug]: Dynamic property of a text layer `fillColor` is not working
### What happened?

When setting a dynamic `fillColor` property on a text layer, the text disappears:
```
        textLayer("**", "textTop") {
            fillColor {
                Color.White
            }
            text {
                topText
            }
        }
``` 

### What Compottie version do you experience the bug on?

2.0.0-beta02

### What platforms are you seeing the problem on?

All

### Does Compottie log anythyng to the stdout / your logger set with `Compottie.logger`?

_No response_

### PR DESCRIPTION
**Pull request by sergeys-opera**
…Document.kt

When setting a value at a specific position in a list, the list must have size up to the given position.

This commit fixes #17.

### CODE REVIEW

File: compottie/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedTextDocument.kt [hunk 1]
```diff
@@ -130,4 +129,11 @@ private fun MutableList<Float>.fill(color : Color) : MutableList<Float> {
...
-}
\ No newline at end of file
+}
+
+private fun MutableList<Float>.growToSize(size: Int): MutableList<Float> {
+    while (this.size < size) add(0f)
+    return this
+}
+
+private fun allocateArrayList(size: Int) = ArrayList<Float>(size).growToSize(size)
```
Comment (alexzhirkevich) [inline compottie/src/commonMain/kotlin/io/github/alexzhirkevich/compottie/internal/animation/AnimatedTextDocument.kt]:
```suggestion
private fun allocateArrayList(size: Int) = List(size) { 0f }
```

**Review by alexzhirkevich — APPROVED** [review]
thanks
